spring:
  datasource:
    url: ${RIPPLE_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/ripple?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${RIPPLE_DATASOURCE_USERNAME:root}
    password: ${RIPPLE_DATASOURCE_PASSWORD:root}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 10
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      stat-view-servlet:
        login-username: ${RIPPLE_DRUID_USERNAME:admin}
        login-password: ${RIPPLE_DRUID_PASSWORD:admin}
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
