server:
  port: ${SERVER_PORT:8883}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/ripple}
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: ripple
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: ${RIPPLE_MAX_FILE_SIZE:100MB}
      max-request-size: ${RIPPLE_MAX_REQUEST_SIZE:100MB}

mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-locations: classpath*:mybatis/config.xml
  type-aliases-package: top.coderak.entity
  global-config:
    meta-object-handler: top.coderak.core.base.config.MyMetaObjectHandler

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  config: classpath:log/log4j2.xml
  level:
    top.coderak.mapper: debug
    top.coderak.core.base.mapper: debug
